version: "3.0"

services:
    db:
        image: mysql:latest
        env_file: .env
        volumes:
            - ${VOLUME_MYSQL_DATA}:/var/lib/mysql
            - ${VOLUME_MYSQL_LOGS}:/var/log/mysql
            - ${VOLUME_MYSQL_CONFIG}/conf.d:/etc/mysql/conf.d
            - ${VOLUME_MYSQL_CONFIG}/mysql.conf.d:/etc/mysql/mysql.conf.d
        ports:
            - ${MYSQL_PORT}:3306
        pid: host
        networks:
            appnet:
                ipv4_address: ${NETWORK_MYSQL}

    mailhog:
        image: mailhog/mailhog
        env_file: .env
        ports:
            - ${MAILHOG_SMTP_PORT}:1025
            - ${MAILHOG_PANEL_PORT}:8025
        networks:
            appnet:
                ipv4_address: ${NETWORK_MAILHOG}

    app:
        build: .
        env_file: .env
        links:
            - db
            - mailhog
        volumes:
            - ${VOLUME_NGINX_WWW}:/var/www/vhosts
            - ${VOLUME_NGINX_VHOSTS}:/etc/nginx/sites-available
            - ${VOLUME_NGINX_LOGS}:/var/log/nginx
            - ${VOLUME_NGINX_CERT}:/usr/local/nginx/certificates
            - ${VOLUME_NGINX_SCRIPTS}:/usr/local/nginx/scripts
            - ${VOLUME_PHP_POOL}:/etc/php/7.1/fpm/pool.d
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        pid: host
        networks:
            appnet:
                ipv4_address: ${NETWORK_APP}
        extra_hosts:
            - ${HOST_MYSQL}:${NETWORK_MYSQL}
            - ${HOST_MAILHOG}:${NETWORK_MAILHOG}

networks:
    appnet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}